spring:
  application:
    name: yearbook

  profiles:
    active: development
  # Banner Text
  banner:
    charset: UTF-8
  # location: classpath:/banner/yearbook.txt
  # Jackson Settings
  jackson:
    time-zone: America/Toronto
    date-format: "yyyy-MM-dd HH:mm:ss"

  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Common Database Settings
  sql:
    init:
      continue-on-error: false
  jpa:
    show-sql: true
    open-in-view: false
    properties:
      jakarta:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        "[format_sql]": true
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
---
# Default Profile
spring:
  config:
    activate:
      on-profile: development

  # Database Settings
  datasource:
    url: ${DEV_DB_URL}
    username: ${DEV_USERNAME}
    password: ${DEV_PASSWORD}
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate
# Logger
logging.level:
  web: DEBUG
  "[com.obsidi.yearbook]": DEBUG

---
# Prod Profile
server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod

  # Database Settings
  datasource:
    url: ${PROD_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
    hikari:
      maximum-pool-size: 2
  jpa:
    hibernate:
      ddl-auto: validate

---
# Test Profile
spring:
  config:
    activate.on-profile: test

  # Database Settings
  sql.init:
    mode: always
    continue-on-error: false
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: sa123#
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
