# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: 3_600_000 # 1 hour
  issuer: 'Academy Cohort 6'
  audience: yearbook
  prefix: 'Bearer '
  excluded.urls: >
    /user/login,
    /user/reset/*,
    /test/**,
    /actuator/**,
    /error,
    /profiles,
    /profile/*
# Client Configuration
client:
  url: https://obsidialumniyearbook.com
  email:
    verify:
      param: user/verifyEmail
      expiration: 86_400_000 # 24 hours
    reset:
      param: user/resetPassword
      expiration: 86_400_000 # 24 hours
    invite:
      param: user/sendInvite
      expiration: 172_800_000 # 48 hours
# H2 Server Configuration
h2.server:
  params: >
    -tcp,
    -tcpAllowOthers,
    -tcpPort,
    9090