name: CD for yearbook

on:
  push:
    tags:
      - 'v**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Build with Maven
        env:
          SPRING_PROFILES_ACTIVE: prod
        run: mvn clean package -Dspring.profiles.active=prod -DskipTests --file backend/pom.xml
      


      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
         name: packaged-application
         path: backend/target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: packaged-application
        path: target/

    - name: Setup key
      id: setup-key
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$DEPLOY_KEY" >> $HOME/key.pem
        chmod 400 $HOME/key.pem

    - name: Copy JAR to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ubuntu
        key: ${{ secrets.DEPLOY_KEY }}
        source: "target/*.jar"
        target: "/home/ubuntu/deployment/"

    - name: Connect SSH and Restart Services
      run: |
        ssh -o StrictHostKeyChecking=no -i $HOME/key.pem ubuntu@ec2-18-117-72-136.us-east-2.compute.amazonaws.com '
          sudo systemctl restart helloworld &&
          sudo systemctl restart nginx
        '
