name: Java CI with Maven and JUnit

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      DEV_USERNAME: ${{ secrets.DEV_USERNAME }}
      DEV_PASSWORD: ${{ secrets.DEV_PASSWORD }}
      DEV_DB_URL: ${{ secrets.DEV_DB_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
      MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Build and test with Maven
        env:
          SPRING_PROFILES_ACTIVE: test
        run: mvn -B clean test --file pom.xml

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: "/surefire-reports/TEST-*.xml"
          format: junit